---
- name: Hello Events
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000

  rules:
    - name: Say Hello
      condition: event.payload.message == "foo"
      action:
        debug:
