---
- name: Hello Events
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000

  rules:
    - name: Run job template
      condition: event.url_check.status_code == 200
      action:
        run_job_template:
          organization: Default
          name: "Demo Job Template"
