---
- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - https://devops.experteam.com.tw
        delay: 10

  rules:
    - name: Run job template
      condition: event.url_check.status_code == 200
      action:
        run_job_template:
          organization: Default
          name: "Demo Job Template"
