---
- name: Hello Events
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - https://devops.experteam.com.tw
        delay: 60

  rules:
    - name: Say Hello
      condition: event.status_code == 200
      action:
        run_job_template:
          organization: Default
          name: Demo Job Template
